name: application-github-actions

on: [push]

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: generate version
        id: generate_version
        uses: paulhatch/semantic-version@v3.1.2
        with:
          # The prefix to use to identify tags
          tag_prefix: "v"
          # A string which, if present in a git commit, indicates that a change represents a
          # major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "v${major}.${minor}.${patch}-${increment}"
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          # change_path: "src/my-service"
          # Named version, will be used as suffix for name version tag
          # namespace: marc-app
      - run: | 
          echo ${{join(steps.generate_version.outputs.*, '\n')}}
          echo "version_tag = ${{ steps.generate_version.outputs.version_tag }}"
          echo "version = ${{ steps.generate_version.outputs.version }}"
          echo ${{ steps.generate_version.outputs.version_tag }} > .version.txt
      - name: Upload version
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: .version.txt

  build:
    name: Build
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Get version
        id: get_version
        run: |
          value=`cat .version.txt`
          echo "::set-output name=VERSION::$value"      
      - run: | 
          echo "version = ${{ steps.get_version.outputs.VERSION }}"  
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Tag version
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ steps.get_version.outputs.VERSION }}"
      - uses: actions/upload-artifact@v2
        with:
          name: playing-with-actions-app.${{ steps.get_version.outputs.version }}
          path: app/build/libs