name: Run application in specific version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0.1'

jobs:
  run:
    name: Run application with specific version
    runs-on: ubuntu-latest
    steps:
      - name: Display version
        run: echo "Running application with version ${{ github.event.intpus.version }}"
      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: playing-with-actions-app.${{ github.event.intpus.version }}
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Run application
        run: java -jar playing-with-actions-app.${{ github.event.intpus.version }}.jar
